apiVersion: jiemi.cr/v1alpha1
kind: Decryptor
metadata:
  name: aws-decryptor
spec:
  provider:
    aws:
      keyId:
        secretName: aws-secret
        key: id
      accessKey:
        secretName: aws-secret
        key: access
      region:
        literal: eu-west-3
  source:
    repository:
      url: https://github.com/shigedangao/gogo.git
    fileToDecrypt: aws/foo.enc.yaml
    sopsPath: aws/.sops.yaml
