apiVersion: jiemi.cr/v1alpha1
kind: Decryptor
metadata:
  name: gcp-decryptor
spec:
  provider:
    gcp:
      serviceAccount:
        secretName: gcp-secret
        key: mask-336418-5d828a98a0a8.json
  source:
    repository:
      url: https://github.com/shigedangao/gogo.git
    fileToDecrypt: gcp/encrypted.yaml
    sopsPath: gcp/.sops.yaml
