apiVersion: jiemi.cr/v1alpha1
kind: Decryptor
metadata:
  name: vault-decryptor
spec:
  provider:
    vault:
      address:
        literal: <>
  source:
    repository:
      url: https://github.com/shigedangao/gogo.git
    fileToDecrypt: test/foo.enc.yaml
    sopsPath: test/.sops.yaml
