apiVersion: jiemi.cr/v1alpha1
kind: Decryptor
metadata:
  name: gcp-decryptor
spec:
  provider:
    gcp:
      secretName: gcp-service-account
      key: sa
  source:
    repository:
      url: https://github.com/shigedangao/gogo.git
    fileToDecrypt: test/foo.enc.yaml
    sopsPath: test/.sops.yaml
