[package]
name = "gen"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "0.8.8"
serde_yaml = "0.8"
kube = { version = "0.68.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.14.0", features = ["v1_22"] }
chrono = "0.4"
base64 = "0.13.0"
async-trait = "0.1.52"

# Only use tokio for test purposes
[dev-dependencies]
tokio = { version = "1.17.0", features = ["full"] }
