name: tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install sops
        run: go install go.mozilla.org/sops/v3/cmd/sops@latest
      - name: prepare env file
        working-directory: krapao
        run: |
          touch Env.toml
          echo GIT_USERNAME='"${{ secrets.GIT_USERNAME }}"' >> Env.toml
          echo GIT_TOKEN='"${{ secrets.GIT_TOKEN }}"' >> Env.toml
          echo GIT_SSH_KEY='"""\n${{ secrets.GIT_SSH_KEY }}\n"""' >> Env.toml
      - uses: nolar/setup-k3d-k3s@v1
        with:
          version: v1.22
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: apply test files for test
        run: |
          kubectl apply -f gen/crd.yaml
          kubectl apply -f example/test/secret.yaml
          kubectl apply -f example/test/decryptor.yaml
      - name: install clippy
        run: rustup component add clippy
      - name: run test on gen crate
        working-directory: gen
        run: cargo build && cargo test
      - name: run test on krapao
        working-directory: krapao
        run: cargo build && cargo test -- --test-threads=1
      - name: run test on miwen
        working-directory: miwen
        run: cargo build && cargo test
      - name: run clippy 
        run: cargo clippy
        